### PR TITLE
Check that migrations are created if necessary

### PR DESCRIPTION
**Pull request by sliverc**
No more missing migrations!

### CODE REVIEW

**Comment by czosel** [comment]
Is this relevant when you're developing purely test-driven and make changes to a model?

**Comment by sliverc** [comment]
Yep it unfortunately is... a use case can happen that missing migrations will be added in 2 different PRs which both have done models changes. This will lead to migrations conflict which can only be solved manually. This happens more than you think... :)

**Comment by czosel** [comment]
I understand - thanks for the clarification!

**Comment by sliverc** [comment]
@czosel finally CI running again.

**Pull request merged**
