### PR TITLE
fix: add custom forms for supervisor and supervisee inlines

### PR DESCRIPTION
**Pull request by trowik**
labels of foreign keys for the supervisor and supervisee inlines
needed to be changed

### CODE REVIEW

**Review by sbor23 — APPROVED** [review]
Looks good, but please shorten the commit message so it fits into one line.

**Comment by winged** [comment]
LGTM as well, but agree with @sbor23 regarding the commit message.

Use the first line as a sort of "subject" (what it does), followed by an empty line, and then some text explaining the change (how is it done, why, etc).

See https://chris.beams.io/posts/git-commit/ and https://www.conventionalcommits.org/en/v1.0.0/

**Comment by winged** [comment]
LGTM as well, but agree with @sbor23 regarding the commit message.

Use the first line as a sort of "subject" (what it does), followed by an empty line, and then some text explaining the change (how is it done, why, etc).

See https://chris.beams.io/posts/git-commit/ and https://www.conventionalcommits.org/en/v1.0.0/

**Comment by trowik** [comment]
Sure, is something like now better?

**Comment by winged** [comment]
> Sure, is something like now better?

Better, and I'll merge it in a second, but I'd have swapped the sentences: If you look at `git log --oneline`, I want to see that the label changed (which was the driving idea) not how it was done (adding custom forms)

**Pull request merged**
