### PR TITLE
Add report statistics end point

### PR DESCRIPTION
**Pull request by sliverc**
For better analysis add following report end points to group reports:
* by user
* by year
* by month
* by customer
* by project
* by task

Instead of a generic approach each statistics has its own custom action as it is expected that those action will be expanded in the future.

### CODE REVIEW

**Comment by anehx** [comment]
The resource names must be plural to be valid and parseable JSON-API..

**Comment by sliverc** [comment]
I have adjusted the resource name, working on the included serializers.

**Comment by sliverc** [comment]
@anehx Additionally added included serializers support.

**Comment by sliverc** [comment]
@anehx Reduced number of queries for all grouping action. Ready for review now.

**Comment by sliverc** [comment]
@anehx As discussed offline moved the statistics end point into their own views in the reports app. Ready for review again.

**Pull request merged**
