### PR TITLE
chore(ci): publish container image to ghcr.io

### LINKED ISSUE #787: Automate pushing container images to ghcr.io
Currently there is no automation for publishing container images.

### PR DESCRIPTION
**Pull request by hairmare**
Fixes #787

### CODE REVIEW

**Comment by trowik** [comment]
I'm not familiar with these actions. Do they only publish images with the latest tag?

**Comment by hairmare** [comment]
the workflow publishes `latest` on the default branch and tagged images on each git tag that matches `v*.*.*`

**Review by trowik — APPROVED** [review]
Alright, nice.
LGTM

**Comment by hairmare** [comment]
i did have a look at the caluma workflow you mention and it reminded me of how i used to publish images a long time ago.

imo the docker/metadata-action solution is superior because it removes complexity from the push step

**Comment by trowik** [comment]
I agree, it looks way cleaner with the docker/metadata-action.

**Pull request merged**
